version: "3"

services:
  web:
    build: "./web"
    ports:
      - "5000:5000"
    links:
      - agrosmart
  agrosmart:
    build: "./db"
    ports:
      - "27017:27017"
  dashboard:
    build: "./dashboard"
    ports:
      - "80:80"